//
//  WILDHostFunctions.h
//  Stacksmith
//
//  Created by Uli Kusterer on 16.04.11.
//  Copyright 2011 Uli Kusterer. All rights reserved.
//

/*!
	@header WILDHostFunctions
	All the custom-syntax functions (including object descriptors) specific to
	Stacksmith are implemented here, along with the syntax to parse them. To
	register them, call:
	
	<pre>
	LEOAddInstructionsToInstructionArray( gStacksmithHostFunctionInstructions, WILD_NUMBER_OF_HOST_FUNCTION_INSTRUCTIONS, &kFirstStacksmithHostFunctionInstruction );
	LEOAddHostFunctionsAndOffsetInstructions( gStacksmithHostFunctions, kFirstStacksmithHostFunctionInstruction );
	</pre>
*/

#include "LEOInstructions.h"
#include "ForgeTypes.h"


enum
{
	WILD_STACK_INSTRUCTION = 0,
	WILD_BACKGROUND_INSTRUCTION,
	WILD_CARD_INSTRUCTION,
	WILD_CARD_FIELD_INSTRUCTION,
	WILD_CARD_BUTTON_INSTRUCTION,
	WILD_CARD_MOVIEPLAYER_INSTRUCTION,
	WILD_CARD_PART_INSTRUCTION,
	WILD_BACKGROUND_FIELD_INSTRUCTION,
	WILD_BACKGROUND_BUTTON_INSTRUCTION,
	WILD_BACKGROUND_MOVIEPLAYER_INSTRUCTION,
	WILD_BACKGROUND_PART_INSTRUCTION,
	WILD_NEXT_CARD_INSTRUCTION,
	WILD_PREVIOUS_CARD_INSTRUCTION,
	WILD_FIRST_CARD_INSTRUCTION,
	WILD_LAST_CARD_INSTRUCTION,
	WILD_NEXT_BACKGROUND_INSTRUCTION,
	WILD_PREVIOUS_BACKGROUND_INSTRUCTION,
	WILD_PUSH_ORDINAL_BACKGROUND_INSTRUCTION,
	WILD_PUSH_ORDINAL_PART_INSTRUCTION,
	WILD_THIS_STACK_INSTRUCTION,
	WILD_THIS_BACKGROUND_INSTRUCTION,
	WILD_THIS_CARD_INSTRUCTION,
	WILD_NUMBER_OF_CARD_BUTTONS_INSTRUCTION,
	WILD_NUMBER_OF_CARD_FIELDS_INSTRUCTION,
	WILD_NUMBER_OF_CARD_MOVIEPLAYERS_INSTRUCTION,
	WILD_NUMBER_OF_CARD_PARTS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_BUTTONS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_FIELDS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_MOVIEPLAYERS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_PARTS_INSTRUCTION,
	WILD_CARD_TIMER_INSTRUCTION,
	WILD_BACKGROUND_TIMER_INSTRUCTION,
	WILD_NUMBER_OF_CARD_TIMERS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_TIMERS_INSTRUCTION,
	WILD_CARD_GRAPHIC_INSTRUCTION,
	WILD_BACKGROUND_GRAPHIC_INSTRUCTION,
	WILD_NUMBER_OF_CARD_GRAPHICS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_GRAPHICS_INSTRUCTION,
	WILD_MESSAGE_BOX_INSTRUCTION,
	WILD_MESSAGE_WATCHER_INSTRUCTION,
	WILD_VARIABLE_WATCHER_INSTRUCTION,
	WILD_CARD_BROWSER_INSTRUCTION,
	WILD_BACKGROUND_BROWSER_INSTRUCTION,
	WILD_NUMBER_OF_CARD_BROWSERS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUND_BROWSERS_INSTRUCTION,
	WILD_NUMBER_OF_CARDS_INSTRUCTION,
	WILD_NUMBER_OF_BACKGROUNDS_INSTRUCTION,
	WILD_NUMBER_OF_STACKS_INSTRUCTION,
	WILD_PUSH_NUMBER_OF_SCREENS_INSTRUCTION,
	WILD_PUSH_SCREEN_INSTRUCTION,
	WILD_PUSH_THIS_PROJECT_INSTRUCTION,
	WILD_PUSH_PROJECT_INSTRUCTION,
	WILD_PUSH_MENU_INSTRUCTION,
	WILD_PUSH_MENUITEM_INSTRUCTION,
	
	WILD_NUMBER_OF_HOST_FUNCTION_INSTRUCTIONS
};


LEOINSTR_DECL(StacksmithHostFunction,WILD_NUMBER_OF_HOST_FUNCTION_INSTRUCTIONS)

extern size_t						kFirstStacksmithHostFunctionInstruction;


extern struct THostCommandEntry	gStacksmithHostFunctions[];
